# Generated by Django 4.0 on 2021-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deadline', models.CharField(max_length=50)),
                ('completed', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
